Repository aspirepress/.github, pull requests merged in 2024-11, with the labels that each got.

#4 spelling and formatting fixes
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  CREDITS.md
  GOVERNANCE.md
  ROADMAP.md
  SECURITY.md
  profile/README.md
  pull_request_template.md
Labels: enhancement

#8 Typos on CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#10 Fixed various typos in ROADMAP.md
  ROADMAP.md
Labels: documentation

#12 Moving items from PR template into Contributor policy
  CONTRIBUTING.md
  pull_request_template.md
Labels: documentation, enhancement

#19 Update README.md
  profile/README.md
Labels: documentation
